### ISSUE TITLE
Update README with contribution guidelines

### ISSUE THREAD

**Issue by abrichr** [MLDSAI/OpenAdapt#133]
We should include:

- https://google.github.io/styleguide/pyguide.html
- https://github.com/psf/black
- others?

**Comment by dianzrong** [comment]
I think we should place these guidelines in a new CONTRIBUTING.md file since I noticed that another open source project [(Python Fire)](https://github.com/google/python-fire/blob/master/CONTRIBUTING.md) did so and that [github](https://github.com/google/python-fire/blob/master/CONTRIBUTING.md) has an article about putting contributing guidelines for open source in a CONTRIBUTING.md file.


> As a maintainer, all you have to do is add a CONTRIBUTING file (or CONTRIBUTING.md if you’re using Markdown) to the root of your repository. Then we will add a link to your file when a contributor creates an Issue or opens a Pull Request.

**Comment by abrichr** [comment]
Agreed! Would you like to take this on?

**Comment by dianzrong** [comment]
@abrichr Sounds good, I will start on it tomorrow!
