### ISSUE TITLE
Explore Falcon LLM

### ISSUE THREAD

**Issue by abrichr** [MLDSAI/OpenAdapt#274]
### Feature request

https://falconllm.tii.ae/

### Motivation

https://news.ycombinator.com/item?id=36350137

**Comment by FFFiend** [comment]
Since we're focusing on trying to get things to run offline and on the CPU (this is where things like LLAMA.cpp come in) there's a rather concerning point on the model card for the 40B model https://huggingface.co/tiiuae/falcon-40b:
```
You will need at least 85-100GB of memory to swiftly run inference with Falcon-40B.
``` 
My next instinct was to check the inference API, but they turned it off.

It also apparently outperforms LLama (still can't ever nail what letters to capitalize in that word :D ) and has a smaller 7B param model which is a bit more reasonable (16 gigs to run) https://huggingface.co/tiiuae/falcon-7b

**Comment by FFFiend** [comment]
This is a HuggingFace Space for their 40B model finetuned for Instructions, https://huggingface.co/spaces/HuggingFaceH4/falcon-chat but the response length seems like its capped for the demo.

**Comment by abrichr** [comment]
Let's wait until the quantized version is available.
